name: Check issue label

on:
  issues:
    types:
      - labeled

permissions: {}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7.0.1
        with:
          script: |
            const labelsToCheck = ['waiting for author', 'need improvement', 'bug 🐛', 'documentation 📖', 'feature 💡', 'question 💬', 'notabug', 'stale', 'wontfix', 'duplicate'];

            const labelToRemove = 'waiting for maintainer';

            const newLabel = context.payload.label.name;

            if (labelsToCheck.includes(newLabel)) {
                const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });

                if (labels.some(label => label.name === labelToRemove)) {
                  await github.rest.issues.removeLabel({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: labelToRemove,
                  });
                }
            }
